language: generic
env:
  global:
    - VERSION="2019.07.1"
    - REVISION="01"
    - DATE=`date +%Y%m%d`
    - MAINTAINER="Claudio Ramirez <pub.claudio@gmail.com>"
    - DEPS="build-essential git lsb-release ruby wget ruby-dev"
    - PREFIX="/opt/rakudo-pkg-for-doc"
    - DOCREPO="https://github.com/perl6/doc.git"
    - ZEFREPO="https://github.com/ugexe/zef.git"
    - PATH="/opt/rakudo-pkg-for-doc/bin:/opt/rakudo-pkg-for-doc/share/perl6/site/bin:$PATH"
    - secure: "Rh31qrnCOND4Cll6JH3P3PDAO4zNrWTwXlbmTEo1u/G6Stbs3Njue3/6Hq5B0udlEPwoM4w3v/VwGN4VELhMC3slav2ch/8nd/xFcbCEAYjubhdvo0R2YlW0GGOfsmRZxt0t/dabWbE9zHCO9nFYMhs0gjOExdOA+qiCXXp33ssqRxC4bW9u3r5ng4MKshXUQaDCQI/7H7bnsdST8G9+/YvNbKwPLoJGc/yvvqKUorYupyzs4IdIIUK4zqNrRzlIQOE6u+IUKPSImb8DHv0PWh56p2RHI6ydN3TIjwBEdmRIqCPL0yPcR1Sk6QtT7xjUYDd6tq5+SmjxQlodORXRIQAWbIJVkso9bplDRYrjBNd4SDD0aXVpcbLJmKXBC48X6Z9zoV6roekRaxU7c7sJfrf76/5C/CTW/FNtKfkkKtatoO69cFwpxlCsd91L2cFYoV/w8fFYZfG2Njr1ZjDMiO1uLqWfXBIjos2Y25hdphMvMqM8/rCGwl5BGObba3SddfU1cLbqImCujdFZoI+X2O4lYsQ2vc/yNjDzMpywAhUP4W7iDjtIt5H21IeOdkM9FPIC2kRXlizejCMYAvTAvq+iPVIAyyf2cVzr6PQ0Wy+YAJm5Gxq9/4NK6fon9yOSmN0X9rIVTEkldq4ohfEF/8gJiBurhHBZNP1NgCdSvI8="
sudo: required
install:
  - set -e
  - sudo apt-get -q update
  - sudo apt-get install -q -y $DEPS
  - wget https://rakudo.perl6.org/downloads/rakudo/rakudo-$VERSION.tar.gz
  - mkdir /var/tmp/rakudo && tar xzf *.tar.gz -C /var/tmp/rakudo --strip=1
  - cd /var/tmp
  - git clone --depth=1 $DOCREPO
  - git clone --depth=1 $ZEFREPO
  - sudo /usr/bin/gem install --no-ri --no-rdoc fpm executable-hooks
script:
  - cd /var/tmp/rakudo
  - sudo perl ./Configure.pl --prefix=$PREFIX --backend=moar --gen-moar
  - sudo make
  - sudo make
  - sudo make install
  - perl6 -v
  - cd /var/tmp/zef && sudo /opt/rakudo-pkg-for-doc/bin/perl6 -Ilib bin/zef install -to=core .
  - sudo ln -s $PREFIX/share/perl6/core/bin/zef $PREFIX/bin/zef
  - cd /var/tmp/doc && sudo env "PATH=$PATH" /opt/rakudo-pkg-for-doc/bin/zef --verbose --deps-only install .
  - export FPM=$(ls -1 /home/travis/.rvm/gems/ruby-*/wrappers/fpm)
  - cd / && sudo $FPM --deb-no-default-config-files --license 'Artistic License 2.0' --description 'Rakudo Perl 6 runtime for perl6/doc CI' --input-type dir --output-type deb --package /var/tmp --name rakudo-pkg-for-doc --maintainer "$MAINTAINER" --version $VERSION --iteration $REVISION --url 'https://perl6.org' --architecture native $PREFIX
before_deploy: sudo chown -R travis:travis /home/travis/ $TRAVIS_BUILD_DIR && cd /
deploy:
  provider: releases
  api_key:
    secure: XMh+KeGDsqCHc74mFGHZiazSjbIA0BtZVk5CZxwv5A45uWmFHrvR0SJOEVDHcgvWAX465B0tDAheh1aHiF89DsUE3GbumkOQ697XrlgCLMfMaXIinI37oGrID/l6eIYIA5mh5GU6W9UUogOxldQzzZb123aeAW7LwxSssNf6hQoy+4vq2ffgJVesR09E/3tt4ZvT9swGoskKZIGM1hftfSdV+82N/pGJZk4ylH7ab5ZuQX3lbL3MZH5L4jZHJfahmA1uK0pwKluhcwVi2SSAYCd8KMRFwJVynnF9YKUCYACt7fxLbY6ZgTY5BmNKNebbbQckRLyw2UjR2G46oYtlZGXOhquM/N1atlZkUSqr62rSmyceYJGpZJ+hWc2s2d4xvxUc1gnaFJUEYXP98ANS4iFHUrzMHHORHARw9dPxQi+mPS73OdbHlfb8MGFksRUfZFwcF3/kltCOeBU/Yb6zhnA5gdTn9OoHwl6xxlArKSpGiMBBmGdkAlBfW1Xz7tCMUyaDSEz+206ibTpTOotudPbYgXY1PnTtaxBCZiNDgS0qb/1MFSlbZjCI0sWd/y/Fe5UXgy8Ov9/t0HTfK6ejaFJ0ek+otTU7R4LxSdtQz4Dm8e8L4QT4+TDY2Vfrpbo0D5FnHj3fvl/pFSE9Ntarbs+N3+bNKKp8jRYSr7BZRZc=
  file_glob: true
  file: "/var/tmp/*"
  skip_cleanup: true
  on:
    repo: nxadm/rakudo-pkg-for-doc
    tags: true
    branches:
      only:
        - /^v20\d{2}\.\d{2}(\.\d+)?-\d+$/
after_deploy:
  - cd /var/tmp/rakudo-pkg; export FILE=`ls -1 *.deb`; curl -T $FILE -unxadm:$BINTRAY_API "https://api.bintray.com/content/nxadm/perl6-doc/rakudo-pkg-for-doc/${RAKUDO_VERSION}-${REVISION}/pool/main/r/rakudo-pkg-for-doc/$FILE;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
