language: generic
env:
  global:
    - VERSION="2018.04.1"
    - REVISION="01"
    - DATE=`date +%Y%m%d`
    - MAINTAINER="Claudio Ramirez <pub.claudio@gmail.com>"
    - DEPS="build-essential git lsb-release ruby wget ruby-dev"
    - PREFIX="/opt/rakudo-pkg-for-doc"
    - DOCREPO="https://github.com/perl6/doc.git"
    - ZEFREPO="https://github.com/ugexe/zef.git"
    - PATH="/opt/rakudo-pkg-for-doc/bin:/opt/rakudo-pkg-for-doc/share/perl6/site/bin:$PATH"
sudo: required
install:
  - set -e
  - sudo apt-get -q update
  - sudo apt-get install -q -y $DEPS
  - wget https://rakudo.perl6.org/downloads/rakudo/rakudo-$VERSION.tar.gz
  - mkdir /var/tmp/rakudo && tar xzf *.tar.gz -C /var/tmp/rakudo --strip=1
  - cd /var/tmp && git clone --depth=1 $DOCREPO
  - sudo /usr/bin/gem install --no-ri --no-rdoc fpm executable-hooks
script:
  - cd /var/tmp/rakudo && sudo perl ./Configure.pl --prefix=$PREFIX --backend=moar --gen-moar
  - sudo make
  - sudo make test
  - sudo make install
  - cd /var/tmp && git clone --depth=1 $ZEFREPO && cd zef
  - sudo $PREFIX/bin/perl6 -Ilib bin/zef --install-to=perl install .
  - sudo ln -s $PREFIX/share/perl6/bin/zef $PREFIX/bin/zef
  - cd /var/tmp/doc && sudo "PATH=$PATH" /opt/rakudo-pkg-for-doc/bin/zef --deps-only install .
  - cd / && sudo /home/travis/.rvm/gems/ruby-2.4.1/gems/fpm-1.9.3/bin/fpm --deb-no-default-config-files --license 'Artistic License 2.0' --description 'Rakudo Perl 6 runtime for perl6/doc CI' --input-type dir --output-type deb --package /var/tmp --name rakudo-pkg-for-doc --maintainer "$MAINTAINER" --version $VERSION --iteration $REVISION --url 'https://perl6.org' --architecture native $PREFIX
  - ls -la /var/tmp/*.deb
  - sudo dpkg -i /var/tmp/*.deb
  - /opt/rakudo-pkg-for-doc/bin/perl6 -v
  - cd /home/travis/build/nxadm/rakudo-pkg-for-doc
before_deploy: perl -pi -e "s/__DATE__/${DATE}/; s/__VERSION__/${VERSION}/; s/__REVISION__/${REVISION}/" .bintray.json
deploy:
  provider: bintray
  file: .bintray.json
  skip_cleanup: true
  user: nxadm
  key:
    secure: "BX5DjWon0RPy5DTgOJsrYnjsO72yEHRReH74Socw4sg91XnYdrJID0RoWveJAV9VpLieiF62R80viL2agQgg8oR7e45YCe+dWEoMnVI7PKUJqh/lcw++/tSMMk2KrzlLhMnKOOfEU1c2iH7DDRV8MY41FYbOnFneey317BgimgZBIm1gwQwgiQevVJHJwmUoV33+BQq0jpXJS2aTztdT2MhAIDarKfkfxItqVVj0auaFk7v7LaMMJPg0E546CNC+xWbPp6U17vBHjMWZ3WSV9cCOD6n76hlmrazoWU8/PSsH9uQTMRxMFyik7SQp9GoaB0/5OlGKbZk8MoxFSlJ/RXtk/bDLE9N6ziIMhaJlglMUvp3fB5HdoDVz/lHoL91Up1xIZG9QyZdio7rpThoxmBZt3YFs9tiVOcr7ceVZFXNB5FFP9e+gmcyPhXswTpnRevGRpL2Bn5rzj7F2PWRWS5Q2VYPa4ZW1838OdWbeLm+R0NRqA7LxM/c6cQz/yFlMjFDyWJcAi8wx6KDyyCrQOaTrRaxPDivP1Q8CrB7SX8Ka5TOc+JHao2QUjUN3X1EKZ1XvSp+80Yg9nSSJTHc/JkaT7HsY8Juq3SC+afKtks7GHxPHQ7yL0isFV+6srOlZTYaa0dpRoRX3pzTmcryHHKu/Hz5KBJr9rHu0fFbcY2s=" 
  on:
    repo: nxadm/rakudo-pkg-for-doc
    tags: true
  branches:
    only:
      - /^v20\d{2}\.\d{2}(\.\d+)?-\d+$/
