language: generic
env:
  global:
    - VERSION="2019.07.1"
    - REVISION="01"
    - DATE=`date +%Y%m%d`
    - MAINTAINER="Claudio Ramirez <pub.claudio@gmail.com>"
    - DEPS="build-essential git lsb-release ruby wget ruby-dev"
    - PREFIX="/opt/rakudo-pkg-for-doc"
    - DOCREPO="https://github.com/perl6/doc.git"
    - ZEFREPO="https://github.com/ugexe/zef.git"
    - PATH="/opt/rakudo-pkg-for-doc/bin:/opt/rakudo-pkg-for-doc/share/perl6/site/bin:$PATH"
    - secure: "Rh31qrnCOND4Cll6JH3P3PDAO4zNrWTwXlbmTEo1u/G6Stbs3Njue3/6Hq5B0udlEPwoM4w3v/VwGN4VELhMC3slav2ch/8nd/xFcbCEAYjubhdvo0R2YlW0GGOfsmRZxt0t/dabWbE9zHCO9nFYMhs0gjOExdOA+qiCXXp33ssqRxC4bW9u3r5ng4MKshXUQaDCQI/7H7bnsdST8G9+/YvNbKwPLoJGc/yvvqKUorYupyzs4IdIIUK4zqNrRzlIQOE6u+IUKPSImb8DHv0PWh56p2RHI6ydN3TIjwBEdmRIqCPL0yPcR1Sk6QtT7xjUYDd6tq5+SmjxQlodORXRIQAWbIJVkso9bplDRYrjBNd4SDD0aXVpcbLJmKXBC48X6Z9zoV6roekRaxU7c7sJfrf76/5C/CTW/FNtKfkkKtatoO69cFwpxlCsd91L2cFYoV/w8fFYZfG2Njr1ZjDMiO1uLqWfXBIjos2Y25hdphMvMqM8/rCGwl5BGObba3SddfU1cLbqImCujdFZoI+X2O4lYsQ2vc/yNjDzMpywAhUP4W7iDjtIt5H21IeOdkM9FPIC2kRXlizejCMYAvTAvq+iPVIAyyf2cVzr6PQ0Wy+YAJm5Gxq9/4NK6fon9yOSmN0X9rIVTEkldq4ohfEF/8gJiBurhHBZNP1NgCdSvI8="
sudo: required
install:
  - set -e
  - id
  - sudo apt-get -q update
  - sudo apt-get install -q -y $DEPS
  - wget https://rakudo.perl6.org/downloads/rakudo/rakudo-$VERSION.tar.gz
  - sudo mkdir -p /work /pkg && sudo chown travis:travis /work /pkg
  - mkdir /work/rakudo && tar xzf *.tar.gz -C /work/rakudo --strip=1
  - cd /work
  - git clone --depth=1 $DOCREPO
  - git clone --depth=1 $ZEFREPO
  - sudo /usr/bin/gem install --no-ri --no-rdoc fpm executable-hooks
  - find /home/travis -name fpm -type f -exec ls -la {} \;
script:
  - cd /work/rakudo
  - sudo perl ./Configure.pl --prefix=$PREFIX --backend=moar --gen-moar
  - sudo make
  - sudo make
  - sudo make install
  - perl6 -v
  - cd /work/zef && sudo /opt/rakudo-pkg-for-doc/bin/perl6 -Ilib bin/zef install -to=core .
  - sudo ln -s $PREFIX/share/perl6/core/bin/zef $PREFIX/bin/zef
  - cd /work/doc && sudo env "PATH=$PATH" /opt/rakudo-pkg-for-doc/bin/zef --verbose --deps-only install .
  - export FPM=$(ls -1 /home/travis/.rvm/gems/ruby-*/gems/fpm-*/bin/fpm) && cd / && sudo $FPM --deb-no-default-config-files --license 'Artistic License 2.0' --description 'Rakudo Perl 6 runtime for perl6/doc CI' --input-type dir --output-type deb --package /pkg --name rakudo-pkg-for-doc --maintainer "$MAINTAINER" --version $VERSION --iteration $REVISION --url 'https://perl6.org' --architecture native $PREFIX
before_deploy: sudo chown -R travis:travis /home/travis /pkg/* $TRAVIS_BUILD_DIR && cd
deploy:
  provider: releases
  api_key:
      secure: nT0r13Sd9mYQSdwUCw1wxQmX4nHSdjG//WYsiThKoXts3viUQuWSe+748C2Rj8lkmQHWg1UvTsDQnRT+iLCstgdSiNYNFqjMtxJN+6QujSAI38Ha+y7wxBHn31rA+Zk9xufH6fDLX/UI/mGkMnF6WGeze0N2IAFhJ4ffO6MkdNGwdyu4md6hcsBe3J5vQG7fJ1VJlr+Vrze4YZfrlfgrg41YhK92STBNXiTceaT00rZFH4wBPO691Z52+LiowUUFhDHyZCKjII1djB71LbIASzLll72GluUGO1tk5olowziUbqSVr0dNyrm0p2rNLmJMpk+hELgktSmZy/qiNv39vQ9C5BFFfYMgUKsIMO6Bdf2Vhspj3Cd5tFMGsByKX8yr4grcEtuVWLvs+7kLWhMUbXPCVEKh4QhZR5qEnwpNSA06F0423LUIOwCRRbvqFWVcWNoHWo1Wco4nB01h9Sync0oay+f2cyQxKVM3PibkNxqLYuBUvChh8gfA9vvBpcwLegONLIrE7PhyJ0dT0JUkun2vp2iW27TX2SgCBMryEtKY8ZcxgQuXTapzbvLPjZ6jjkLR04rGG02MLdfrjuzoZR19mstHMHo19+AaIzQEUuc/6ZioM5VxZnPhxQ7SHCYLREZ1WwXRUxHlmo8eYhI2W+AEcZnzM7Q0Wn/fq1JTcP0=
  file_glob: true
  file: "/pkg/*"
  skip_cleanup: true
  on:
    repo: nxadm/rakudo-pkg-for-doc
    tags: true
    branches:
      only:
        - /^v20\d{2}\.\d{2}(\.\d+)?(-\d+)?$/
after_deploy:
  - cd /pkg; export FILE=`ls -1 *.deb`; curl -T $FILE -unxadm:$BINTRAY_API "https://api.bintray.com/content/nxadm/perl6-doc/rakudo-pkg-for-doc/${RAKUDO_VERSION}-${REVISION}/pool/main/r/rakudo-pkg-for-doc/$FILE;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
