language: generic
env:
  global:
  - VERSION="2018.03"
  - REVISION="01"
  - MANTAINER="Claudio Ramirez <pub.claudio@gmail.com>"
  - DEPS="build-essential git graphviz lsb-release ruby wget ruby-dev"
  - PREFIX="/opt/rakudo-pkg-for-doc"
  - DOCREPO="https://github.com/perl6/doc.git"
  - ZEFREPO="https://github.com/ugexe/zef.git"
sudo: required
install:
  - sudo apt-get update && sudo apt-get -u dist-upgrade -y
  - sudo apt-get install -y $DEPS
  - wget https://rakudo.perl6.org/downloads/rakudo/rakudo-$VERSION.tar.gz
  - mkdir /var/tmp/rakudo && tar xzf *.tar.gz -C /var/tmp/rakudo --strip=1
  - cd /var/tmp && git clone --depth=1 $DOCREPO
script:
  - cd /var/tmp/rakudo
  - sudo perl ./Configure.pl --prefix=$PREFIX --backend=moar --gen-moar
  - sudo make test
  - sudo make install
  - cd /var/tmp && git clone --depth= 1 $ZEFREPO && cd zef
  - $PREFIX/bin/perl6 -Ilib bin/zef --install-to=perl install .
  - ln -s $PREFIX/share/perl6/bin/zef $PREFIX/bin/zef
  - cd /var/tmp/doc
  - zef --deps-only install .
  - cd /
  - sudo fpm \
        --deb-no-default-config-files \
        --license 'Artistic License 2.0' \
        --description 'Rakudo Perl 6 runtime for perl6/doc CI' \
        --input-type dir \
        --output-type deb \
        --package /var/tmp \
        --name rakudo-pkg-for-doc \
        --maintainer $MAINTAINER \
        --version $VERSION \
        --iteration $REVISION \
        --url 'https://perl6.org \
        --architecture native \
        $PREFIX
  - ls -la *.deb
  - sudo dpkg -i /var/tmp/*.deb
